apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: firstapp
  name: firstapp
  namespace: firstapp
spec:
  host: "firstapp.apps.ocp-services.example.com"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: svc-firstapp
    weight: 100
status: {}
