---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: firstapp
  name: firstapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: firstapp
---
